/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ffos.view;

import com.github.javafaker.Faker;
import ffos.controller.ObradaKulen;
import ffos.controller.ObradaMesar;
import ffos.controller.ObradaMjesto;
import ffos.model.Kulen;
import ffos.model.Mesar;
import ffos.model.Mjesto;
import static java.awt.Frame.NORMAL;
import javax.swing.JOptionPane;

/**
 *
 * @author marija
 */
public class Izbornik extends javax.swing.JFrame {
    private Faker faker;

    /**
     * Creates new form Izbornik
     */
    public Izbornik() {
        initComponents();
        faker = new Faker();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnUnosMesar = new javax.swing.JButton();
        btnUnosMjesto = new javax.swing.JButton();
        btnUnosKulen = new javax.swing.JButton();
        btnProzorMesar = new javax.swing.JButton();
        btnProzorMjesto = new javax.swing.JButton();
        btnProzorKulen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel1.setText("Kuleni u sušionici");

        btnUnosMesar.setText("Unos Mesar");
        btnUnosMesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnosMesarActionPerformed(evt);
            }
        });

        btnUnosMjesto.setText("Unos Mjesto");
        btnUnosMjesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnosMjestoActionPerformed(evt);
            }
        });

        btnUnosKulen.setText("Unos Kulen");
        btnUnosKulen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnosKulenActionPerformed(evt);
            }
        });

        btnProzorMesar.setText("Prozor Mesar");
        btnProzorMesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProzorMesarActionPerformed(evt);
            }
        });

        btnProzorMjesto.setText("Prozor Mjesto");
        btnProzorMjesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProzorMjestoActionPerformed(evt);
            }
        });

        btnProzorKulen.setText("Prozor Kulen");
        btnProzorKulen.setToolTipText("");
        btnProzorKulen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProzorKulenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUnosMesar)
                    .addComponent(btnUnosMjesto)
                    .addComponent(btnUnosKulen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnProzorKulen)
                    .addComponent(btnProzorMjesto)
                    .addComponent(btnProzorMesar))
                .addGap(97, 97, 97))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnProzorMesar)
                        .addGap(65, 65, 65)
                        .addComponent(btnProzorMjesto)
                        .addGap(70, 70, 70)
                        .addComponent(btnProzorKulen))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnUnosMesar)
                        .addGap(65, 65, 65)
                        .addComponent(btnUnosMjesto)
                        .addGap(70, 70, 70)
                        .addComponent(btnUnosKulen)))
                .addContainerGap(97, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnUnosMesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnosMesarActionPerformed
        // TODO add your handling code here:
        
        ObradaMesar om = new ObradaMesar();
        Mesar m; 
        for(int i = 0; i<22; i++){
            m = new Mesar();
            m.setIme(faker.name().firstName());
            m.setPrezime(faker.name().lastName());
            om.setEntitet(m);
            
            try {
                om.create();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(getRootPane(), ex.getMessage());
            }
           
        }
    }//GEN-LAST:event_btnUnosMesarActionPerformed

    private void btnUnosMjestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnosMjestoActionPerformed
        // TODO add your handling code here:
        ObradaMjesto om = new ObradaMjesto();
        Mjesto m; 
        for(int i = 0; i<30; i++){
            m = new Mjesto();
            m.setNaziv(faker.country().capital());
            m.setPostanskiBroj(faker.number().numberBetween(10000, 10000));
            om.setEntitet(m);
            
            try {
                om.create();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(getRootPane(), ex.getMessage());
            }
           
        }
    }//GEN-LAST:event_btnUnosMjestoActionPerformed

    private void btnUnosKulenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnosKulenActionPerformed
        // TODO add your handling code here:
        
        ObradaMesar om = new ObradaMesar();
        ObradaMjesto omj = new ObradaMjesto();
        ObradaKulen ok = new ObradaKulen ();
        
        Kulen k;
        for(int i = 0; i<47; i++) {
            k = new Kulen();
            k.setBroj(faker.number().randomDigit());
            k.setDatumProizvodnje(faker.date().birthday());
            k.setMesar(om.read().get(faker.random().nextInt(1, 22)));
            k.setMjesto(omj.read().get(faker.random().nextInt(1, 30)));
            ok.setEntitet(k);
            try {
                ok.create();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(getRootPane(), ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnUnosKulenActionPerformed

    private void btnProzorMesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProzorMesarActionPerformed
        // TODO add your handling code here:
        new ProzorMesar().setVisible(true);
    }//GEN-LAST:event_btnProzorMesarActionPerformed

    private void btnProzorMjestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProzorMjestoActionPerformed
        // TODO add your handling code here:
        new ProzorMjesto().setVisible(true);
    }//GEN-LAST:event_btnProzorMjestoActionPerformed

    private void btnProzorKulenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProzorKulenActionPerformed
        // TODO add your handling code here:
        new ProzorKulen().setVisible(true);
    }//GEN-LAST:event_btnProzorKulenActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProzorKulen;
    private javax.swing.JButton btnProzorMesar;
    private javax.swing.JButton btnProzorMjesto;
    private javax.swing.JButton btnUnosKulen;
    private javax.swing.JButton btnUnosMesar;
    private javax.swing.JButton btnUnosMjesto;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
