/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ffos.view;

import com.github.javafaker.Faker;
import ffos.controller.ObradaMjesto;
import ffos.controller.ObradaSport;

/**
 *
 * @author marija
 */
public class Izbornik extends javax.swing.JFrame {

    /**
     * Creates new form Izbornik
     */
    public Izbornik() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnUnosMjesto = new javax.swing.JButton();
        btnUnosSport = new javax.swing.JButton();
        btnUnosOsoba = new javax.swing.JButton();
        btnCrudMjesto = new javax.swing.JButton();
        btnCrudSport = new javax.swing.JButton();
        btnCrudOsoba = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnUnosMjesto.setText("Unos Mjesto");
        btnUnosMjesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnosMjestoActionPerformed(evt);
            }
        });

        btnUnosSport.setText("Unos Sport");
        btnUnosSport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnosSportActionPerformed(evt);
            }
        });

        btnUnosOsoba.setText("Unos Osoba");

        btnCrudMjesto.setText("CRUD Mjesto");

        btnCrudSport.setText("CRUD Sport");
        btnCrudSport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrudSportActionPerformed(evt);
            }
        });

        btnCrudOsoba.setText("CRUD Osoba");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUnosMjesto)
                    .addComponent(btnUnosSport)
                    .addComponent(btnUnosOsoba))
                .addGap(152, 152, 152)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCrudOsoba)
                    .addComponent(btnCrudSport)
                    .addComponent(btnCrudMjesto))
                .addContainerGap(229, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUnosMjesto)
                    .addComponent(btnCrudMjesto))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUnosSport)
                    .addComponent(btnCrudSport))
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUnosOsoba)
                    .addComponent(btnCrudOsoba))
                .addContainerGap(150, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUnosMjestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnosMjestoActionPerformed
        // TODO add your handling code here:
        ObradaMjesto om = new ObradaMjesto();
        Faker faker = new Faker();
        
        for(int i=0; i<21; i++){
            om.setNew();
            om.setPodaci(faker.country().capital());
            try {
                om.create();
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_btnUnosMjestoActionPerformed

    private void btnUnosSportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnosSportActionPerformed
        // TODO add your handling code here:
        ObradaSport os = new ObradaSport();
        Faker faker = new Faker();
        
        for(int i=0; i<43; i++){
            os.setNew();
            os.setPodaci(faker.team().name(), faker.team().sport());
            try {
                os.create();
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_btnUnosSportActionPerformed

    private void btnCrudSportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrudSportActionPerformed
        // TODO add your handling code here:
        new FormaSport().setVisible(true);
    }//GEN-LAST:event_btnCrudSportActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrudMjesto;
    private javax.swing.JButton btnCrudOsoba;
    private javax.swing.JButton btnCrudSport;
    private javax.swing.JButton btnUnosMjesto;
    private javax.swing.JButton btnUnosOsoba;
    private javax.swing.JButton btnUnosSport;
    // End of variables declaration//GEN-END:variables
}
